### ISSUE TITLE
Problems with makefile on os x

### ISSUE THREAD

**Issue by Degola** [deepfryed/beanstalk-client#18]
$ make
gcc -Wall -Wno-sign-compare -g -I. -fPIC -c -o beanstalk.o beanstalk.c
g++ -Wall -Wno-sign-compare -g -I. -fPIC -c -o beanstalkcpp.o beanstalk.cc
g++ -shared -Wl,-soname,libbeanstalk.so.1 -o libbeanstalk.dylib  beanstalk.o beanstalkcpp.o
ld: unknown option: -soname
collect2: ld returned 1 exit status
make: *** [libbeanstalk.dylib] Error 1

**Comment by deepfryed** [comment]
fixed in #19
