### ISSUE TITLE
Why through poll instead of epoll to achieve?

### ISSUE THREAD

**Issue by xuanskyer** [deepfryed/beanstalk-client#34]
Why through poll instead of epoll to achieve?
As far as I know, epoll performance is better

**Comment by deepfryed** [comment]
beanstalk-client is generic, you can use any polling mechanism. See bs_start_polling() function and the examples.

btw epoll is Linux specific. You could detect platform and use epoll in Linux or kqueue in BSD.

**Comment by xuanskyer** [comment]
Thanks for reply
